<a href="https://colab.research.google.com/github/Fedoseevale/Statistica_Homework8/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задача 1**

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy

Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [2]:
import numpy as np
import scipy.stats as stats

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [5]:
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)

Вычисление ковариации "вручную":

In [7]:
cov

9157.839999999997

Смещенная ковариация:

In [8]:
np.cov(zp, ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Несмещенная ковариация:

In [9]:
cov2 = np.cov(zp, ks, ddof = 1)

In [10]:
cov2

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [11]:
std_zp = np.std(zp, ddof = 1)

In [12]:
std_zp

62.31318747531162

In [13]:
std_ks = np.std(ks, ddof = 1)

In [14]:
std_ks

183.99544076477068

Вычисление коэффициента корреляции Пирсона "вручную" (через несмещённую ковариацию):

In [15]:
corrcoef = cov2/(std_zp*std_ks)

In [16]:
corrcoef

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

Вычисление коэффициента корреляции Пирсона посредством встроенной функции  (через несмещённую ковариацию):

In [29]:
np.corrcoef(zp, ks, ddof = 1)

<ipython-input-29-31af8145ff04>:1: DeprecationWarning: bias and ddof have no effect and are deprecated
  np.corrcoef(zp, ks, ddof = 1)


array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])